const fs = require('fs-extra')
if (fs.existsSync('.env')) require('dotenv').config({ path: __dirname+'/.env' })


//═══════[Required Variables]════════\\
global.audio= "" ;  
global.video= "" ;
global.port =process.env.PORT
global.appUrl=process.env.APP_URL || ""                       // put your app url here,
global.email ="samsamsun789@gmail.com"
global.location="Lahore,Pakistan."
global.mongodb= process.env.MONGODB_URI || ""
global.allowJids= process.env.ALLOW_JID || "null" 
global.blockJids= process.env.BLOCK_JID || "120363023983262391@g.us"
global.DATABASE_URI = process.env.DATABASE_URL || ""

global.timezone= process.env.TZ || process.env.TIME_ZONE || "Asia/Karachi";
global.github=process.env.GITHUB|| "https://github.com/SuhailTechInfo/Suhail-Md";
global.gurl  =process.env.GURL  || "https://whatsapp.com/channel/0029Va9thusJP20yWxQ6N643";
global.website=process.env.GURL || "https://whatsapp.com/channel/0029Va9thusJP20yWxQ6N643" ; 
global.THUMB_IMAGE = process.env.THUMB_IMAGE || process.env.IMAGE || "https://telegra.ph/file/d5b1c3544fedc23e11a06.jpg" ; // SET LOGO FOR IMAGE 



global.devs = "923323988258" // Developer Contact
global.sudo = process.env.SUDO ? process.env.SUDO.replace(/[\s+]/g, '') : "null";
global.owner= process.env.OWNER_NUMBER ? process.env.OWNER_NUMBER.replace(/[\s+]/g, '') : "923323988258";




//========================= [ BOT SETTINGS ] =========================\\
global.style = process.env.STYLE   || '5',  // put '1' to "5" here to check bot styles
global.flush = process.env.FLUSH   || "false"; // Make it "true" if bot not responed
global.gdbye = process.env.GOODBYE || "false"; 
global.wlcm  = process.env.WELCOME || "false";  // Make it "false" for disable WELCOME 

global.warncount = process.env.WARN_COUNT || 3,
global.disablepm = process.env.DISABLE_PM || "false",
global.MsgsInLog = process.env.MSGS_IN_LOG|| "false", // "true"  to see messages , "log" to open logs , "false" to hide logs messages
global.userImages= process.env.USER_IMAGES|| "text",
global.waPresence= process.env.WAPRESENCE ||  "set according to your need" ; // 'unavailable' | 'available' | 'composing' | 'recording' | 'paused'


//========================= [ AUTO READ MSGS & CMDS ] =========================\\
global.readcmds = process.env.READ_COMMAND || "false"
global.readmessage = process.env.READ_MESSAGE || "false"
global.readmessagefrom = process.env.READ_MESSAGE_FROM || "null,923xxxxxxxx";


//========================= [ AUTO SAVE & READ STATUS ] =========================\\
global.read_status = process.env.AUTO_READ_STATUS || "false"
global.save_status = process.env.AUTO_SAVE_STATUS || "false"
global.save_status_from =  process.env.SAVE_STATUS_FROM  || "null,923xxxxxxxx";
global.read_status_from =  process.env.READ_STATUS_FROM  ||  "923184474176,923xxxxxxxx";

global.api_smd = "https://api-smd-1.vercel.app"
global.scan = "https://suhail-md-vtsf.onrender.com/";

module.exports = {

  menu: process.env.MENU || "", /**  Available @MENU @Schemes 1: Aztec_Md, 2: A17_Md, 3: Suhail-Md Default ---------- If Not Choose then it Randomely Pic One Of Them Each time **/

  HANDLERS: process.env.PREFIX  || ".",
  BRANCH  : process.env.BRANCH  || "main",
  VERSION : process.env.VERSION || "V.1.2.8",
  caption : process.env.CAPTION || "©sᴜʜᴀɪʟ²²¹-ᴍᴅ" , // ```『 ᴘᴏᴡᴇʀᴇᴅ ʙʏ sᴜʜᴀɪʟ²²¹-ᴍᴅ 』```", //*『sᴜʙsᴄʀɪʙᴇ • sᴜʜᴀɪʟ ᴛᴇᴄʜ』*\n youtube.com/@suhailtechinfo0"),
 
  author : process.env.PACK_AUTHER|| "Suhail-MD",
  packname: process.env.PACK_NAME || "♥️",
  botname : process.env.BOT_NAME  || "sᴜʜᴀɪʟ-ᴍᴅ",
  ownername:process.env.OWNER_NAME|| "It'x Suhail",

  sessionName:process.env.SESSION_ID || "SUHAIL_07_41_03_23_ewogICJjcmVkcy5qc29uIjogIntcbiAgXCJub2lzZUtleVwiOiB7XG4gICAgXCJwcml2YXRlXCI6IHtcbiAgICAgIFwidHlwZVwiOiBcIkJ1ZmZlclwiLFxuICAgICAgXCJkYXRhXCI6IFtcbiAgICAgICAgNTYsXG4gICAgICAgIDQ4LFxuICAgICAgICAxODYsXG4gICAgICAgIDIyMCxcbiAgICAgICAgODEsXG4gICAgICAgIDE0LFxuICAgICAgICAxMjgsXG4gICAgICAgIDExLFxuICAgICAgICA1MixcbiAgICAgICAgOTksXG4gICAgICAgIDgxLFxuICAgICAgICAxMTIsXG4gICAgICAgIDEyMixcbiAgICAgICAgMjUsXG4gICAgICAgIDg0LFxuICAgICAgICAxNzksXG4gICAgICAgIDIxNSxcbiAgICAgICAgMjQ0LFxuICAgICAgICAyMTgsXG4gICAgICAgIDQ1LFxuICAgICAgICAxMzQsXG4gICAgICAgIDEyMSxcbiAgICAgICAgMTg0LFxuICAgICAgICAzMCxcbiAgICAgICAgMjAwLFxuICAgICAgICAxMDgsXG4gICAgICAgIDE0NCxcbiAgICAgICAgMjM3LFxuICAgICAgICAxNDcsXG4gICAgICAgIDYsXG4gICAgICAgIDExNSxcbiAgICAgICAgNzJcbiAgICAgIF1cbiAgICB9LFxuICAgIFwicHVibGljXCI6IHtcbiAgICAgIFwidHlwZVwiOiBcIkJ1ZmZlclwiLFxuICAgICAgXCJkYXRhXCI6IFtcbiAgICAgICAgNDQsXG4gICAgICAgIDExNyxcbiAgICAgICAgODEsXG4gICAgICAgIDUsXG4gICAgICAgIDIxNyxcbiAgICAgICAgMTA4LFxuICAgICAgICAxNzcsXG4gICAgICAgIDIsXG4gICAgICAgIDE1MSxcbiAgICAgICAgMTU4LFxuICAgICAgICAxMjUsXG4gICAgICAgIDYyLFxuICAgICAgICAyNyxcbiAgICAgICAgMTk2LFxuICAgICAgICAxMDUsXG4gICAgICAgIDI1MCxcbiAgICAgICAgMixcbiAgICAgICAgNzAsXG4gICAgICAgIDg1LFxuICAgICAgICAxNDAsXG4gICAgICAgIDk5LFxuICAgICAgICAyMDUsXG4gICAgICAgIDIxMSxcbiAgICAgICAgMjIsXG4gICAgICAgIDIwMSxcbiAgICAgICAgMTkyLFxuICAgICAgICAyNDMsXG4gICAgICAgIDY3LFxuICAgICAgICAxNjcsXG4gICAgICAgIDIzNSxcbiAgICAgICAgNjIsXG4gICAgICAgIDIyXG4gICAgICBdXG4gICAgfVxuICB9LFxuICBcInBhaXJpbmdFcGhlbWVyYWxLZXlQYWlyXCI6IHtcbiAgICBcInByaXZhdGVcIjoge1xuICAgICAgXCJ0eXBlXCI6IFwiQnVmZmVyXCIsXG4gICAgICBcImRhdGFcIjogW1xuICAgICAgICAyMTYsXG4gICAgICAgIDEzMyxcbiAgICAgICAgNjIsXG4gICAgICAgIDE3NyxcbiAgICAgICAgMjM2LFxuICAgICAgICAxMjUsXG4gICAgICAgIDY3LFxuICAgICAgICAxOSxcbiAgICAgICAgODIsXG4gICAgICAgIDI0MyxcbiAgICAgICAgOSxcbiAgICAgICAgMjA1LFxuICAgICAgICAxODgsXG4gICAgICAgIDEzLFxuICAgICAgICAxNzAsXG4gICAgICAgIDEwNCxcbiAgICAgICAgMTAsXG4gICAgICAgIDIsXG4gICAgICAgIDE0MixcbiAgICAgICAgMTA2LFxuICAgICAgICAxMTMsXG4gICAgICAgIDczLFxuICAgICAgICA2NSxcbiAgICAgICAgMTgxLFxuICAgICAgICAxNTAsXG4gICAgICAgIDI4LFxuICAgICAgICAyMDcsXG4gICAgICAgIDM5LFxuICAgICAgICAyMjQsXG4gICAgICAgIDEyLFxuICAgICAgICAxNTgsXG4gICAgICAgIDExM1xuICAgICAgXVxuICAgIH0sXG4gICAgXCJwdWJsaWNcIjoge1xuICAgICAgXCJ0eXBlXCI6IFwiQnVmZmVyXCIsXG4gICAgICBcImRhdGFcIjogW1xuICAgICAgICA0LFxuICAgICAgICAxNjksXG4gICAgICAgIDE4MixcbiAgICAgICAgODMsXG4gICAgICAgIDIyMSxcbiAgICAgICAgMjQ4LFxuICAgICAgICAxNzgsXG4gICAgICAgIDExOCxcbiAgICAgICAgMTY3LFxuICAgICAgICAyMDIsXG4gICAgICAgIDIwOCxcbiAgICAgICAgMTAyLFxuICAgICAgICAxLFxuICAgICAgICAxMDQsXG4gICAgICAgIDE0LFxuICAgICAgICAxMDUsXG4gICAgICAgIDE3MixcbiAgICAgICAgOTAsXG4gICAgICAgIDIxOSxcbiAgICAgICAgMjA4LFxuICAgICAgICAyNDUsXG4gICAgICAgIDEzLFxuICAgICAgICAxMTgsXG4gICAgICAgIDE5OCxcbiAgICAgICAgMjI0LFxuICAgICAgICA5MixcbiAgICAgICAgMTc3LFxuICAgICAgICAxMixcbiAgICAgICAgMjMyLFxuICAgICAgICAyNDEsXG4gICAgICAgIDE1NSxcbiAgICAgICAgM1xuICAgICAgXVxuICAgIH1cbiAgfSxcbiAgXCJzaWduZWRJZGVudGl0eUtleVwiOiB7XG4gICAgXCJwcml2YXRlXCI6IHtcbiAgICAgIFwidHlwZVwiOiBcIkJ1ZmZlclwiLFxuICAgICAgXCJkYXRhXCI6IFtcbiAgICAgICAgODAsXG4gICAgICAgIDM5LFxuICAgICAgICAyMTUsXG4gICAgICAgIDE0NyxcbiAgICAgICAgMTUwLFxuICAgICAgICAyMjYsXG4gICAgICAgIDQ4LFxuICAgICAgICAxOTcsXG4gICAgICAgIDIzMyxcbiAgICAgICAgODcsXG4gICAgICAgIDkzLFxuICAgICAgICAzMSxcbiAgICAgICAgMjM4LFxuICAgICAgICAyNDUsXG4gICAgICAgIDE0MixcbiAgICAgICAgMjMsXG4gICAgICAgIDkzLFxuICAgICAgICAyMTYsXG4gICAgICAgIDQ2LFxuICAgICAgICAzMCxcbiAgICAgICAgNTQsXG4gICAgICAgIDE2OCxcbiAgICAgICAgMTkwLFxuICAgICAgICAzMCxcbiAgICAgICAgMTQyLFxuICAgICAgICAyNDcsXG4gICAgICAgIDIyMyxcbiAgICAgICAgMjM2LFxuICAgICAgICA0MCxcbiAgICAgICAgMjI1LFxuICAgICAgICA0NyxcbiAgICAgICAgMTE0XG4gICAgICBdXG4gICAgfSxcbiAgICBcInB1YmxpY1wiOiB7XG4gICAgICBcInR5cGVcIjogXCJCdWZmZXJcIixcbiAgICAgIFwiZGF0YVwiOiBbXG4gICAgICAgIDIyOSxcbiAgICAgICAgMTYzLFxuICAgICAgICAyLFxuICAgICAgICAxOTEsXG4gICAgICAgIDEsXG4gICAgICAgIDEyMixcbiAgICAgICAgMTE2LFxuICAgICAgICAyMCxcbiAgICAgICAgODAsXG4gICAgICAgIDU0LFxuICAgICAgICAyMTAsXG4gICAgICAgIDIxNSxcbiAgICAgICAgMTI0LFxuICAgICAgICAxNTEsXG4gICAgICAgIDUzLFxuICAgICAgICA4NSxcbiAgICAgICAgOTQsXG4gICAgICAgIDIyMSxcbiAgICAgICAgNjYsXG4gICAgICAgIDUwLFxuICAgICAgICAyMTQsXG4gICAgICAgIDMyLFxuICAgICAgICAxMzQsXG4gICAgICAgIDc2LFxuICAgICAgICAxNDQsXG4gICAgICAgIDEwNSxcbiAgICAgICAgOTcsXG4gICAgICAgIDczLFxuICAgICAgICAyMjMsXG4gICAgICAgIDcxLFxuICAgICAgICAyMDIsXG4gICAgICAgIDEwMlxuICAgICAgXVxuICAgIH1cbiAgfSxcbiAgXCJzaWduZWRQcmVLZXlcIjoge1xuICAgIFwia2V5UGFpclwiOiB7XG4gICAgICBcInByaXZhdGVcIjoge1xuICAgICAgICBcInR5cGVcIjogXCJCdWZmZXJcIixcbiAgICAgICAgXCJkYXRhXCI6IFtcbiAgICAgICAgICAxOTIsXG4gICAgICAgICAgNzksXG4gICAgICAgICAgMTc2LFxuICAgICAgICAgIDc2LFxuICAgICAgICAgIDE2MyxcbiAgICAgICAgICAxMzcsXG4gICAgICAgICAgMTU4LFxuICAgICAgICAgIDE5NSxcbiAgICAgICAgICA4MSxcbiAgICAgICAgICAyLFxuICAgICAgICAgIDU2LFxuICAgICAgICAgIDE1OCxcbiAgICAgICAgICA2OSxcbiAgICAgICAgICAxOCxcbiAgICAgICAgICAxODcsXG4gICAgICAgICAgMTY1LFxuICAgICAgICAgIDIzOSxcbiAgICAgICAgICAyMDcsXG4gICAgICAgICAgNTgsXG4gICAgICAgICAgMjAsXG4gICAgICAgICAgMTEzLFxuICAgICAgICAgIDE3MyxcbiAgICAgICAgICAxMjAsXG4gICAgICAgICAgMjMzLFxuICAgICAgICAgIDE4MSxcbiAgICAgICAgICAyMTYsXG4gICAgICAgICAgMTc2LFxuICAgICAgICAgIDc5LFxuICAgICAgICAgIDI0MixcbiAgICAgICAgICAyNDksXG4gICAgICAgICAgMTY1LFxuICAgICAgICAgIDEyN1xuICAgICAgICBdXG4gICAgICB9LFxuICAgICAgXCJwdWJsaWNcIjoge1xuICAgICAgICBcInR5cGVcIjogXCJCdWZmZXJcIixcbiAgICAgICAgXCJkYXRhXCI6IFtcbiAgICAgICAgICAwLFxuICAgICAgICAgIDEsXG4gICAgICAgICAgMjE1LFxuICAgICAgICAgIDEzNSxcbiAgICAgICAgICAxMjUsXG4gICAgICAgICAgMTQ3LFxuICAgICAgICAgIDI0MCxcbiAgICAgICAgICA4OCxcbiAgICAgICAgICAxNDAsXG4gICAgICAgICAgMjUxLFxuICAgICAgICAgIDIyMSxcbiAgICAgICAgICAxMTgsXG4gICAgICAgICAgMjAwLFxuICAgICAgICAgIDEwLFxuICAgICAgICAgIDExOSxcbiAgICAgICAgICAxMCxcbiAgICAgICAgICAxNjYsXG4gICAgICAgICAgMzAsXG4gICAgICAgICAgMTEzLFxuICAgICAgICAgIDE5NyxcbiAgICAgICAgICAxNDYsXG4gICAgICAgICAgMjMxLFxuICAgICAgICAgIDI0MSxcbiAgICAgICAgICAyNTEsXG4gICAgICAgICAgMTIwLFxuICAgICAgICAgIDQ3LFxuICAgICAgICAgIDEwMSxcbiAgICAgICAgICA3MSxcbiAgICAgICAgICAyNDcsXG4gICAgICAgICAgMzIsXG4gICAgICAgICAgMTksXG4gICAgICAgICAgMTE3XG4gICAgICAgIF1cbiAgICAgIH1cbiAgICB9LFxuICAgIFwic2lnbmF0dXJlXCI6IHtcbiAgICAgIFwidHlwZVwiOiBcIkJ1ZmZlclwiLFxuICAgICAgXCJkYXRhXCI6IFtcbiAgICAgICAgOSxcbiAgICAgICAgMjI4LFxuICAgICAgICA1NCxcbiAgICAgICAgNyxcbiAgICAgICAgMzgsXG4gICAgICAgIDg2LFxuICAgICAgICA3NCxcbiAgICAgICAgNzgsXG4gICAgICAgIDEwLFxuICAgICAgICA2MSxcbiAgICAgICAgMjI5LFxuICAgICAgICAyNDQsXG4gICAgICAgIDE3MyxcbiAgICAgICAgMjUzLFxuICAgICAgICAyMzcsXG4gICAgICAgIDY0LFxuICAgICAgICAxMzIsXG4gICAgICAgIDczLFxuICAgICAgICA4LFxuICAgICAgICA0LFxuICAgICAgICA4OSxcbiAgICAgICAgMzMsXG4gICAgICAgIDI0MSxcbiAgICAgICAgMjA2LFxuICAgICAgICAxNzAsXG4gICAgICAgIDIwMixcbiAgICAgICAgMTAsXG4gICAgICAgIDUxLFxuICAgICAgICA5MixcbiAgICAgICAgMjksXG4gICAgICAgIDM5LFxuICAgICAgICA3MyxcbiAgICAgICAgMjMzLFxuICAgICAgICA2MCxcbiAgICAgICAgMjQyLFxuICAgICAgICA0MSxcbiAgICAgICAgMCxcbiAgICAgICAgNjEsXG4gICAgICAgIDIzMCxcbiAgICAgICAgMjQ1LFxuICAgICAgICAxMyxcbiAgICAgICAgMTE0LFxuICAgICAgICA5NixcbiAgICAgICAgOTcsXG4gICAgICAgIDI0MyxcbiAgICAgICAgNCxcbiAgICAgICAgMTI2LFxuICAgICAgICAxNjcsXG4gICAgICAgIDEwMCxcbiAgICAgICAgMTA1LFxuICAgICAgICAxNDEsXG4gICAgICAgIDIyOSxcbiAgICAgICAgMTc4LFxuICAgICAgICA3NSxcbiAgICAgICAgMjU1LFxuICAgICAgICAxNTEsXG4gICAgICAgIDIxMCxcbiAgICAgICAgMTk5LFxuICAgICAgICAyMzksXG4gICAgICAgIDY0LFxuICAgICAgICA4NixcbiAgICAgICAgNjUsXG4gICAgICAgIDE0NSxcbiAgICAgICAgNFxuICAgICAgXVxuICAgIH0sXG4gICAgXCJrZXlJZFwiOiAxXG4gIH0sXG4gIFwicmVnaXN0cmF0aW9uSWRcIjogMTE3LFxuICBcImFkdlNlY3JldEtleVwiOiBcImh2UGJQeEdmS3I4Z09qMytFYUQ3SjdZK2FZTS96dXlHQ3dWUmFMRy9nbFU9XCIsXG4gIFwicHJvY2Vzc2VkSGlzdG9yeU1lc3NhZ2VzXCI6IFtdLFxuICBcIm5leHRQcmVLZXlJZFwiOiAzMSxcbiAgXCJmaXJzdFVudXBsb2FkZWRQcmVLZXlJZFwiOiAzMSxcbiAgXCJhY2NvdW50U3luY0NvdW50ZXJcIjogMCxcbiAgXCJhY2NvdW50U2V0dGluZ3NcIjoge1xuICAgIFwidW5hcmNoaXZlQ2hhdHNcIjogZmFsc2VcbiAgfSxcbiAgXCJkZXZpY2VJZFwiOiBcInA1Z21mSWU3UkNxM2x2YU9vRXRTMWdcIixcbiAgXCJwaG9uZUlkXCI6IFwiZmIwMjBiNjktN2M1Yy00NDAwLWI1YmUtMmVjZTA1MDdiMThmXCIsXG4gIFwiaWRlbnRpdHlJZFwiOiB7XG4gICAgXCJ0eXBlXCI6IFwiQnVmZmVyXCIsXG4gICAgXCJkYXRhXCI6IFtcbiAgICAgIDEwNixcbiAgICAgIDMyLFxuICAgICAgNDYsXG4gICAgICAxNTgsXG4gICAgICA3MixcbiAgICAgIDE3MCxcbiAgICAgIDIxNCxcbiAgICAgIDIwMixcbiAgICAgIDIwNCxcbiAgICAgIDEyMSxcbiAgICAgIDE0NSxcbiAgICAgIDE0MCxcbiAgICAgIDIxNixcbiAgICAgIDIxLFxuICAgICAgMTI3LFxuICAgICAgMTEzLFxuICAgICAgMTk3LFxuICAgICAgMTkzLFxuICAgICAgMTQ3LFxuICAgICAgMTgyXG4gICAgXVxuICB9LFxuICBcInJlZ2lzdGVyZWRcIjogdHJ1ZSxcbiAgXCJiYWNrdXBUb2tlblwiOiB7XG4gICAgXCJ0eXBlXCI6IFwiQnVmZmVyXCIsXG4gICAgXCJkYXRhXCI6IFtcbiAgICAgIDg2LFxuICAgICAgMjUyLFxuICAgICAgMjMwLFxuICAgICAgMTA2LFxuICAgICAgMjQ3LFxuICAgICAgMTI4LFxuICAgICAgMTgyLFxuICAgICAgNDAsXG4gICAgICA3MSxcbiAgICAgIDg5LFxuICAgICAgMTQyLFxuICAgICAgODMsXG4gICAgICAyMDcsXG4gICAgICAzMCxcbiAgICAgIDIzLFxuICAgICAgNzQsXG4gICAgICAxODQsXG4gICAgICA0LFxuICAgICAgMTk5LFxuICAgICAgMTAzXG4gICAgXVxuICB9LFxuICBcInJlZ2lzdHJhdGlvblwiOiB7fSxcbiAgXCJwYWlyaW5nQ29kZVwiOiBcIllQTUFBWlY3XCIsXG4gIFwibWVcIjoge1xuICAgIFwiaWRcIjogXCI5MjMzMjM5ODgyNTg6NDBAcy53aGF0c2FwcC5uZXRcIixcbiAgICBcImxpZFwiOiBcIjY5NzAzNTk0Njc2NDM3OjQwQGxpZFwiXG4gIH0sXG4gIFwiYWNjb3VudFwiOiB7XG4gICAgXCJkZXRhaWxzXCI6IFwiQ05mVitNZ0JFSzcyL3I0R0dBRWdBQ2dBXCIsXG4gICAgXCJhY2NvdW50U2lnbmF0dXJlS2V5XCI6IFwiZ0VhQm5pNzkrVnJGdUg5LzZmQlcwTVl6bThYclg4RmdXRWVSOTZadktWMD1cIixcbiAgICBcImFjY291bnRTaWduYXR1cmVcIjogXCJGamlVYVNKYTZhWmRVaTVYcG5uaFhjYXNUN01vYk01TVMrdjlHMFhvUVMwMWk3V0s1ZEFwUVlvWVUxZVcxMDByZ09va2F2dENGSmRQblR4M29FanJBdz09XCIsXG4gICAgXCJkZXZpY2VTaWduYXR1cmVcIjogXCJUajJQTG8yeTEwd1JyQ0x6SG9PUWVDblhjV3lhdTluT0VsV1F1bUpJM2ZwOTRqZFhaZ3FaR08zTEhPL0pOZWEwZXZPVU1wVTh0Y2RyNFBLTmkza3pBUT09XCJcbiAgfSxcbiAgXCJzaWduYWxJZGVudGl0aWVzXCI6IFtcbiAgICB7XG4gICAgICBcImlkZW50aWZpZXJcIjoge1xuICAgICAgICBcIm5hbWVcIjogXCI5MjMzMjM5ODgyNTg6NDBAcy53aGF0c2FwcC5uZXRcIixcbiAgICAgICAgXCJkZXZpY2VJZFwiOiAwXG4gICAgICB9LFxuICAgICAgXCJpZGVudGlmaWVyS2V5XCI6IHtcbiAgICAgICAgXCJ0eXBlXCI6IFwiQnVmZmVyXCIsXG4gICAgICAgIFwiZGF0YVwiOiBbXG4gICAgICAgICAgNSxcbiAgICAgICAgICAxMjgsXG4gICAgICAgICAgNzAsXG4gICAgICAgICAgMTI5LFxuICAgICAgICAgIDE1OCxcbiAgICAgICAgICA0NixcbiAgICAgICAgICAyNTMsXG4gICAgICAgICAgMjQ5LFxuICAgICAgICAgIDkwLFxuICAgICAgICAgIDE5NyxcbiAgICAgICAgICAxODQsXG4gICAgICAgICAgMTI3LFxuICAgICAgICAgIDEyNyxcbiAgICAgICAgICAyMzMsXG4gICAgICAgICAgMjQwLFxuICAgICAgICAgIDg2LFxuICAgICAgICAgIDIwOCxcbiAgICAgICAgICAxOTgsXG4gICAgICAgICAgNTEsXG4gICAgICAgICAgMTU1LFxuICAgICAgICAgIDE5NyxcbiAgICAgICAgICAyMzUsXG4gICAgICAgICAgOTUsXG4gICAgICAgICAgMTkzLFxuICAgICAgICAgIDk2LFxuICAgICAgICAgIDg4LFxuICAgICAgICAgIDcxLFxuICAgICAgICAgIDE0NSxcbiAgICAgICAgICAyNDcsXG4gICAgICAgICAgMTY2LFxuICAgICAgICAgIDExMSxcbiAgICAgICAgICA0MSxcbiAgICAgICAgICA5M1xuICAgICAgICBdXG4gICAgICB9XG4gICAgfVxuICBdLFxuICBcInBsYXRmb3JtXCI6IFwiYW5kcm9pZFwiLFxuICBcImxhc3RBY2NvdW50U3luY1RpbWVzdGFtcFwiOiAxNzQyNzE1Njk5LFxuICBcIm15QXBwU3RhdGVLZXlJZFwiOiBcIkFBQUFBQkFGXCJcbn0iLAogICJhcHAtc3RhdGUtc3luYy1rZXktQUFBQUFCQUYuanNvbiI6ICJ7XCJrZXlEYXRhXCI6XCJTcWxHVEdnK1lxYXNRblcvTUFKcUVSZnZEcDlJcG1OcmNIZkNOeXo4YmNrPVwiLFwiZmluZ2VycHJpbnRcIjp7XCJyYXdJZFwiOjQyMTQwNzQ0NyxcImN1cnJlbnRJbmRleFwiOjEsXCJkZXZpY2VJbmRleGVzXCI6WzAsMV19LFwidGltZXN0YW1wXCI6XCIxNzQyNzE1NzAzNDUwXCJ9Igp9",  // PUT SESSION ID HERE 
  errorChat : process.env.ERROR_CHAT || "",
  KOYEB_API : process.env.KOYEB_API  || "false",

  REMOVE_BG_KEY : process.env.REMOVE_BG_KEY  || "",
  OPENAI_API_KEY: process.env.OPENAI_API_KEY || "",
  HEROKU_API_KEY: process.env.HEROKU_API_KEY || "",
  HEROKU_APP_NAME:process.env.HEROKU_APP_NAME|| "",
  antilink_values:process.env.ANTILINK_VALUES|| "all",
  HEROKU: process.env.HEROKU_APP_NAME && process.env.HEROKU_API_KEY,

  aitts_Voice_Id : process.env.AITTS_ID || "37",
  ELEVENLAB_API_KEY: process.env.ELEVENLAB_API_KEY || "",
  WORKTYPE: process.env.WORKTYPE||process.env.MODE || "public",
  LANG: process.env.THEME ? process.env.THEME.toUpperCase() : "SUHAIL",



};




























global.isMongodb = false; 
let file = require.resolve(__filename)
fs.watchFile(file, () => { fs.unwatchFile(file);console.log(`Update'${__filename}'`);delete require.cache[file];	require(file); })
 

// ========================= [ Disables in V.1.2.8 ] ===============================\\  
  //style : process.env.STYLE || "2",  // put '1' & "2" here to check bot styles
  //readmessage:process.env.READ_MESSAGE|| "false",
  //warncount: process.env.WARN_COUNT || 3,
  //userImages:process.env.USER_IMAGES|| "text",  // SET IMAGE AND VIDEO URL FOR BOT MENUS 
  //disablepm: process.env.DISABLE_PM || "false",
  //MsgsInLog: process.env.MSGS_IN_LOG|| "false", // "true"  to see messages , "log" to open logs , "false" to hide logs messages
  //readcmds:process.env.READ_COMMANDS|| "false", 
  //alwaysonline:process.env.WAPRESENCE|| "unavailable", // 'unavailable' | 'online' | 'composing' | 'recording' | 'paused'
  //read_status: process.env.AUTO_READ_STATUS || "false",
  //save_status: process.env.AUTO_SAVE_STATUS || "false",
 
